<?php
return array(
	"name"=>"Name",
	"summary"=>"Summary",
	"state"=>"State",
	"down_speed"=>"Down Speed",
	"up_speed"=>"Upload Speed",
	"peers"=>"Peers",
	"downloaded"=>"Downloaded",
	"uploaded"=>"Uploaded",
	"full_size"=>"Full size",
	"control"=>"CONTROL",
	"uploading"=>"Uploading",
	"downloading"=>"Downloading",
	"starting"=>"Starting...",
	"stopping"=>"Stopping...",
	"start"=>"START",
	"stop"=>"STOP",
	"delete"=>"DELETE",
	"free"=>"Free",
	"used"=>"Used",
	"total"=>"Total",
	"loading"=>"Loading...",
	"confirm_delete"=>"Do you really want to delete?",
	"torrent_details"=>"Torrent details",
	"downloaded_have"=> "Content have",
	"session_up"=>"Session uploaded",
	"session_down"=>"Session downloaded",
	"ratio"=> "Ratio",
	"path"=>"Path",
	"hash"=> "Info hash",
	"error" => "Error",
	"no_error" => "No error",
        "change_language"=>"Change language",
        "change_theme"=>"Change theme",
        "upload_torrent"=>"Add torrent"
);

