<?php
return array(
	"name"=>"Név",
	"summary"=>"Öszegzés",
	"state"=>"Állapot",
	"down_speed"=>"Letöltés",
	"up_speed"=>"Feltöltés",
	"peers"=>"Csatlakozók",
	"downloaded"=>"Letöltve",
	"uploaded"=>"Feltöltve",
	"full_size"=>"Teljes méret",
	"control"=>"IRÁNYÍTÁS",
	"uploading"=>"Feltöltés",
	"downloading"=>"Letöltés",
	"starting"=>"Indítás...",
	"stopping"=>"Leállítás...",
	"start"=>"INDÍTÁS",
	"stop"=>"LEÁLLÍTÁS",
	"delete"=>"TÖRLÉS",
	"free"=>"Szabad",
	"used"=>"Használt",
	"total"=>"Teljes",
	"loading"=>"Töltés...",
	"confirm_delete"=>"Valóban törölni szeretnéd a torrentet?",
	"torrent_details"=>"Torrent részletei",
	"downloaded_have"=> "Tartalom letöltve",
	"session_up"=>"Utolsó indítás óta feltöltve",
	"session_down"=>"Utolsó indítás óta letöltve",
	"ratio"=> "Arány",
	"path"=>"Útvonal",
	"hash"=> "Info hash",
	"error" => "Hiba",
	"no_error" => "Nincs hiba",
        "change_language"=>"Nyelv választása",
        "change_theme"=>"Megjelenés választása",
        "upload_torrent"=>"Torrent hozzáadása",
        "target_directory"=>"Cél könyvtár"
);

